#!/bin/sh
#
LOCALTIME=$(date +"%D %T")

cat << EOF
  _____         _   _   _____     _
 |   | |___ ___| |_| |_|   | |___| |_
 | | | | . |  _|  _|   | | | | -_|  _|
 |_|___|___|_| |_| |_|_|_|___|___|_|

 Local-time: $LOCALTIME

EOF
