#!/bin/sh
#
UPTIME_DAYS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 / 86400)
UPTIME_HOURS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 / 3600)
UPTIME_MINUTES=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 % 3600 / 60)

cat << EOF
 Name...............: `cat /etc/update-motd.d/motd_servername | awk '{print $1}'`
 Hostname...........: `cat /proc/sys/kernel/hostname`
 Distro.............: `lsb_release -d | awk  '{print $2,$4}'`
 Version............: `uname -r`
 Uptime.............: $UPTIME_DAYS days, $UPTIME_HOURS hours, $UPTIME_MINUTES minutes

EOF
